"""Initial migration.

Revision ID: 429ca0dbf938
Revises: 
Create Date: 2022-05-11 20:02:12.929680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429ca0dbf938'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('createdAt', sa.Integer(), nullable=False),
    sa.Column('ip', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validators')
    # ### end Alembic commands ###
